# Gate PRs on the GitHub Actions workflow "CI"
status = ["CI build successful"]

# Consider the build as failed if it takes more than half an hour to finish
timeout_sec = 1800

# Require at least 1 up to date approval before allowing `bors r+`
required_approvals = 1
up_to_date_approvals = true

# Remove the personal branches after they're merged
delete_merged_branches = true
