# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "criticalup-cli"
version = "1.1.0"
edition = "2021"
repository = "https://github.com/ferrocene/criticalup"
homepage = "https://github.com/ferrocene/criticalup"
authors = ["The CriticalUp Developers"]
description = "CriticalUp is the official tool to download and install Ferrocene"

[package.metadata.dist]
dist = false

[[test]]
name = "cli"
path = "tests/cli/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["std", "derive", "help", "usage"] }
criticaltrust = { path = "../criticaltrust" }
criticalup-core = { path = "../criticalup-core" }
futures.workspace = true
owo-colors = { version = "4.0.0", default-features = false, features = ["supports-colors"] }
serde_json = "1.0.117"
tar = "0.4.40"
thiserror = "1.0.61"
xz2 = "0.1.7"
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
time = { version = "0.3.36", features = ["std", "serde", "serde-well-known", "macros"] }
walkdir.workspace = true

[dev-dependencies]
insta = { version = "1.39.0", features = ["filters"] }
mock-download-server = { path = "../mock-download-server" }
serde = { version = "1.0.203", features = ["derive"] }
tempfile.workspace = true
regex = "1.10.4"

[target.x86_64-pc-windows-msvc.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_System_Console"] }
winapi = "0.3.9"
