# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "criticalup-core"
version = "0.0.0"
edition = "2021"

build = "build.rs"

[dependencies]
criticaltrust = { path = "../criticaltrust" }
log = "0.4.14"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "rustls-tls-native-roots"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
toml_edit = { version = "0.13.4", features = ["serde"] }
sha2 = { version = "0.10" }
dirs = { version = "5.0.1", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.23.1"

[dev-dependencies]
mock-download-server = { path = "../mock-download-server" }
tempfile = "3.3.0"
