# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "criticalup-core"
version = "0.0.0"
edition = "2021"

build = "build.rs"

[dependencies]
criticaltrust = { path = "../criticaltrust" }
log = "0.4.21"
reqwest = { version = "0.12.4", default-features = false, features = ["blocking", "json", "rustls-tls", "rustls-tls-native-roots"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
toml_edit = { version = "0.22.13", features = ["serde"] }
sha2 = { version = "0.10.8" }
dirs = { version = "5.0.1", default-features = false }

[dev-dependencies]
mock-download-server = { path = "../mock-download-server" }
tempfile = "3.10.1"
